// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    var defaults;
    defaults = {
      name: 'maxmertkit',
      state: 'initialized',
      enabled: true,
      theme: 'primary'
    };
    return $.kit = (function() {

      function kit(el, options) {
        this.el = el;
        this.options = options;
        this.$el = $(this.el);
        this.options = $.extend({}, defaults, this.options);
        this.init();
      }

      kit.prototype.init = function() {
        return this.setOptions(this.options);
      };

      kit.prototype.setOptions = function(options) {
        if (!(options != null)) {
          options = this.options;
        }
        return $.each(options, function() {
          if ($.isFunction(value)) {
            return setMethod(key, value);
          } else {
            return setOption(key, value);
          }
        });
      };

      kit.prototype.setOption = function(key, value) {
        if ((key != null) && (value != null)) {
          switch (key) {
            case 'theme':
              this.$el.removeClass(this.options.theme).addClass("-" + value + "-");
          }
          return this.options[key] = value;
        }
      };

      kit.prototype.setMethod = function(event, handler) {
        return this.$el.bind("" + event + "." + this.name, handler);
      };

      kit.prototype.enable = function() {
        return setOption('enabled', true);
      };

      kit.prototype.disable = function() {
        return setOption('enabled', false);
      };

      kit.prototype.pushInstanse = function() {
        return this.abbys.push(this.el);
      };

      return kit;

    })();
  });

}).call(this);
